version : '3.2'

services:
  web:
    build: './web'
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.6
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: someDB
      MYSQL_USER: someUser
      MYSQL_PASSWORD: Pa$$w0rd
